server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  cloud:
    nacos:
      server-addr: 192.168.232.128:8848 # nacos地址
  redis:
    host: localhost
    post: 6379
    database: 10
# todo nacos的用户名跟密码

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.ychat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 用户接口文档
    description: "信息"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ychat.chat.controller

ychat:
  jwt:
    location: classpath:ychat.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/login
      - /items/**