server:
  port: 8081

websocket:
  port: 8866

spring:
  application:
    name: chat
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  cloud:
    nacos:
      server-addr: 192.168.232.128:8848 # nacos地址
  redis:
    host: 192.168.232.128
    post: 6379
    database: 10
  # RocketMQ 相关配置
rocketmq:
  # 指定 nameServer
  name-server: 192.168.232.128:9876
  # Producer 生产者
  producer:
    group: my-group  # 指定发送者组名
    send-message-timeout: 3000 # 发送消息超时时间，单位：毫秒。默认为 3000 。
    compress-message-body-threshold: 4096 # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    max-message-size: 4194304 # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false




# todo nacos的用户名跟密码

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.ychat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 用户接口文档
    description: "信息"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ychat.chat.controller

ychat:
  jwt:
    location: classpath:ychat.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/login
      - /items/**