server:
  port: 8084
spring:
  application:
    name: user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${ychat.db.host}:3306/ychat-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${ychat.db.pw}
  cloud:
    nacos:
      server-addr: 192.168.232.128:8848 # nacos地址
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.ychat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 用户接口文档
    description: "信息"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ychat.user.controller
ychat:
  jwt:
    location: classpath:ychat.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m