server:
  port: 8081

spring:
  application:
    name: chat
  cloud:
    nacos:
      server-addr: 192.168.232.128:8848 # nacos地址
  data:
    mongodb:
      uri:mongodb://192.168.232.128:27097/ychat
# todo nacos的用户名跟密码

logging:
  level:
    com.ychat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 盆友圈接口文档
    description: "信息"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.ychat.chat.controller
